
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import PreLoader from "@/components/PreLoader";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     
    >
      <body >
        <PreLoader/>
        <Header />
        
        {children}
        <Footer />
        
        </body>
    </html>
  );
}
